"""Generate cacheable, module-level CUDA kernels for lA/lB/lC = 0..6.

Run from any directory: python tools/generate_df_algo11_cuda.py
Only kernels actually used by a basis are JIT compiled. Keep this generator and
the generated module together in changes to scratch sizing or tier selection.

The same kernels serve DF_algo=11 and DF_algo=12: ``masked``/``mask`` select the
far-field primitive-pair mask of algorithm 12 (see df_algo11_cuda_core).
"""
from itertools import product
from pathlib import Path


def generate():
    text = ['"""Generated by tools/generate_df_algo11_cuda.py; do not edit by hand."""\n',
            'from numba import cuda, float64\n',
            'from .df_algo11_cuda_core import evaluate_item\n\n',
            'KERNELS = {}\n']
    args = ('orbital, auxiliary, shells, aux_shells, pairs, items, offsets, values, data_x, data_w, '
            'masked, mask')
    for a, b, c in product(range(7), repeat=3):
        n = (a + 1) * (a + 2) * (b + 1) * (b + 2) * (c + 1) * (c + 2) // 8
        cooperative = n > 540
        stride = 128 if cooperative else 1
        space = 'shared' if cooperative else 'local'
        name = f'build_{a}_{b}_{c}'
        text.append(f'\n\n@cuda.jit(cache=True)\ndef {name}({args}):\n')
        text.append('    item = cuda.blockIdx.x\n    lane = cuda.threadIdx.x\n' if cooperative
                    else '    item = cuda.grid(1)\n    lane = 0\n')
        text.append('    if item >= items.shape[0]:\n        return\n')
        for arr in ('roots', 'weights'):
            text.append(f'    {arr} = cuda.{space}.array({(a + b + c) // 2 + 1}, float64)\n')
        for arr in ('gx', 'gy', 'gz'):
            text.append(f'    {arr} = cuda.{space}.array(({a + b + 1}, {c + 1}), float64)\n')
        for arr in ('sx', 'sy', 'sz'):
            text.append(f'    {arr} = cuda.{space}.array(({a + 1}, {b + 1}, {c + 1}), float64)\n')
        for arr in ('accum', 'tmp'):
            text.append(f'    {arr} = cuda.local.array({(n + stride - 1) // stride}, float64)\n')
        text.append(f'    evaluate_item(item, lane, {stride}, {cooperative}, {args},\n'
                    '                  roots, weights, gx, gy, gz, sx, sy, sz, accum, tmp)\n')
        text.append(f'\nKERNELS[{a}, {b}, {c}] = ({name}, {128 if cooperative else 32}, {cooperative})\n')
    return ''.join(text)


if __name__ == '__main__':
    target = Path(__file__).resolve().parents[1] / 'pyfock/Integrals/df_algo11_cuda_kernels.py'
    target.write_text(generate(), encoding='utf-8')
